//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OduncIslemleri
    {
        public int Islem_Id { get; set; }
        public string TC_Kimlik_No { get; set; }
        public string ISBN_No { get; set; }
        public System.DateTime Verilme_Tarihi { get; set; }
        public System.DateTime Teslim_Tarihi { get; set; }
        public Nullable<System.DateTime> Gercek_Teslim_Tarihi { get; set; }
        public string Durum { get; set; }
        public Nullable<decimal> Ceza_Ucreti { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
