//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.OduncIslemleri = new HashSet<OduncIslemleri>();
        }
    
        public string TC_Kimlik_No { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<System.DateTime> Dogum_Tarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Cep_Telefonu { get; set; }
        public string Eposta_Adresi { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> Eklenme_Tarihi { get; set; }
        public Nullable<bool> Blokeli_Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncIslemleri> OduncIslemleri { get; set; }
    }
}
